name: frontend
   
on:
  push:
    branches: [ main ] 

jobs:
  docker-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout front-end repo
        uses: actions/checkout@v4
        with:
          path: frontend
        
      - name: Checkout back-end repo
        uses: actions/checkout@v4
        with:
          repository: Bashar-OP/CI_CD_Back
          path: backend

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Frontend image
        run: |
           cd frontend
           docker build -t ghcr.io/${{ github.repository }}/frontend:latest .
           cd ..

      - name: Push Frontend image
        run: docker push ghcr.io/${{ github.repository }}/frontend:latest

      - name: Build Backend image
        run: |
           cd backend
           docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest .
           cd ..

      - name: Push Backend image
        run: docker push ghcr.io/${{ github.repository_owner }}/backend:latest




        



        







      
  
