name: frontend

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  docker-run:
    runs-on: self-hosted

    steps:
      - name: Change dir to repo dir
        run: cd /home/bashar-alquos/Desktop/Training/DevOps/3.CI_CD/'apptraining 2'

      - name: Run docker compose
        run: docker compose up

     


        




        



        







      
  
