name: frontend

on:

  push:
    branches: [ main ]

jobs:
  docker-run:
    runs-on: self-hosted

    steps:
      - name: Access pwd
        run: |
          echo "Bash is working"


        




        



        







      
  
