name: frontend

on:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  docker-run:
    runs-on: self-hosted

    steps:
      - name: Change dir to repo dir
        run: cd ../../..

      - name: Run docker compose
        run: pwd

     


        




        



        







      
  
