name: frontend

on:

  push:
    branches: [ main ]

jobs:
  docker-run:
    runs-on: self-hosted

    steps:
      - name: Access pwd
        run: |
          echo "Bash is working"
          cd /home/bashar-alquos/Desktop/Training/DevOps/3.CI_CD/apptraining
          docker-compose up


        




        



        







      
  
