name: frontend

on:

  push:
    branches: [ main ]

jobs:
  docker-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Access pwd
        run: |
          pwd
          ls -R /home/abc/Desktop/Training/DevOps/
          ls -al


        




        



        







      
  
