name: frontend

on:

  push:
    branches: [ main ]

jobs:
  docker-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Access 
        run: |
          cd ~/home/bashar-alquos/Desktop/Training/DevOps/3.CI_CD/apptraining
          docker-compose up -d
          docker-compose down




        



        







      
  
